### ISSUE TITLE
IDK

### ISSUE THREAD

**Issue by Deosaju** [microsoft/vscode-azurevirtualmachines#224] opened 2021-03-26 14:38 UTC
Does this occur consistently? 
Repro steps:

1.i have credits in my account but cant use a virtual machine 
2.have two subscription but are disabled 

Action: azureVirtualMachines.createVirtualMachineAdvanced
Error type: MissingSubscriptionRegistration
Error Message: The subscription is not registered to use namespace 'Microsoft.Compute'. See https://aka.ms/rps-not-found for how to register subscriptions.

Version: 0.3.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.54.3
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:16:21586
extension.bundle.js:16:129786extension.bundle.js:16:129786
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by nturinski** [comment] 2021-04-08 19:20
If you follow the steps here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types, you should be able to register `Microsoft.Compute` and resolve your issue.

Please reopen if that doesn't resolve your issue!

Dupe of https://github.com/microsoft/vscode-azurevirtualmachines/issues/212

**Closed by nturinski** 2021-04-08 19:20 UTC
