### ISSUE TITLE
Fail to create a Linux virtual machine with "Oracle Linux 8.4(LVM)" image and "Microsoft RRDC Lab 1" location

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurevirtualmachines#292] opened 2022-01-20 09:02 UTC
**OS:** All
**Build Version:** 20220119.2
**Regression:** Not a regression

**Repro Steps:**
1. F1 -> Create Virtual Machine...(Advanced) -> Enter a name -> Linux -> Select **Oracle Linux 8.4(LVM)** image -> Default username -> Empty for passphrase -> Select **Microsoft RRDC Lab 1** location.
2. Check whether succeeds to create a Linux virtual machine.

**Expect:**
Succeed to create a Linux virtual machine.

**Actual:**
Fail to create a Linux virtual machine.
![image](https://user-images.githubusercontent.com/57662131/150299715-82715444-6acd-4729-b39b-4b35bd1eed18.png)

**More Info:**
1. This issue also reproduces when creating a virtual machine with **SUSE Enterprise Linux 8.2**, **Debian 11 "Bullseye"**, **Data Science Virtual Machine -Ubuntu 18.04** and **Windows Server 2022 Datacenter: Azure Edition** images.
2. This issue doesn't reproduce for other locations.

**Comment by v-xinda** [comment] 2022-03-24 10:22
@alexweininger  Verified this issue on the latest build 20220323.3, it still reproduces.

**Comment by wwlorey** [comment] 2022-04-06 22:39
Closing as duplicate of https://github.com/microsoft/vscode-azurevirtualmachines/issues/307

**Closed by wwlorey** 2022-04-06 22:39 UTC
Labels: AT-CTI
