### ISSUE TITLE
[Suggestion] Remove the unsupported location from the location list when creating a VM

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurevirtualmachines#200] opened 2021-02-03 08:33 UTC
**OS:** All
**Build:** 20210202.4

**Repro Steps:**
Try to create a VM with location "West US 3".

**Actual:**
An error "The provided location 'westus3' is not available for resource group." occurs.
![image](https://user-images.githubusercontent.com/45614674/106719551-65175c00-663d-11eb-95b0-707ef36451af.png)

**Suggestion:**
Remove the unsupported location from the location list.

**Comment by nturinski** [comment] 2021-02-10 22:18
Closing as a duplicate of this issue: https://github.com/microsoft/vscode-azurevirtualmachines/issues/94

**Closed by nturinski** 2021-02-10 22:18 UTC
Labels: AT-CTI, P1
