### ISSUE TITLE
VS code error while connecting using add ssh key

### ISSUE THREAD

**Issue by restlessankyyy** [microsoft/vscode-azurevirtualmachines#99] opened 2020-04-25 14:26 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureVirtualMachines.addSshKey
Error type: Error
Error Message: Internal error: Expected value to be neither null nor undefined: id

Version: 0.1.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code - Insiders
Product Version: 1.45.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
nonNullValue extension.bundle.js:1:147357
Object.nonNullValueAndProp extension.bundle.js:1:147588
VirtualMachineTreeItem.<anonymous> extension.bundle.js:1:217766
fulfilled extension.bundle.js:1:215989
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment] 2020-04-29 21:54
Hi @restlassankyyy

Thanks for reporting.  Could you provide repro steps?

**Comment by nturinski** [comment] 2020-08-21 01:47
Dupe of https://github.com/microsoft/vscode-azurevirtualmachines/issues/104

**Closed by nturinski** 2020-08-21 01:47 UTC
Labels: needs more info
