### ISSUE TITLE
SSH Key creation fails when ~/.ssh doesn't exist

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurevirtualmachines#97] opened 2020-04-08 22:11 UTC
```sh
Error: command "ssh-keygen -t rsa -b 4096 -f "C:\Users\username\.ssh\keyname_rsa" -N *** failed with exit code "1":
Saving key "C:\\Users\\username\\.ssh\\keyname_rsa" failed: No such file or directory
```

**Comment by EricJizbaMSFT** [comment] 2020-04-08 22:55
Dupe of https://github.com/microsoft/vscode-azurevirtualmachines/issues/87

**Closed by EricJizbaMSFT** 2020-04-08 22:55 UTC
