### ISSUE TITLE
"Connect to Host" via it's private vlan address, not public address

### ISSUE THREAD

**Issue by petecog** [microsoft/vscode-azurevirtualmachines#339] opened 2022-07-07 15:12 UTC
version 	0.6.2

Is it possible (if not this is a feature request) to connect to a VM listed under the Resources via it's private ip address (e.g. the one on the vnet) rather than the public.

I'm setting up a bunch of VMs in a closed off vnet (only accessible via a vpn connector on that vnet). The VMs do not have a public ip (disassociated) or at least will have port 22 inaccessible

erroniously posted here originally, sorry. https://github.com/microsoft/vscode-node-azure-pack/issues/34

**Comment by alexweininger** [comment] 2022-07-13 22:17
Unfortunately, this isn't currently possible. Closing as duplicate of #273

**Closed by alexweininger** 2022-07-13 22:17 UTC
