### ISSUE TITLE
Creating virtual Machine

### ISSUE THREAD

**Issue by tjbhan** [microsoft/vscode-azurevirtualmachines#101] opened 2020-04-28 18:39 UTC
Does this occur consistently? Yes
Repro steps:

1. When I click create machine at the last step in the process this error occours
2.

Action: azureVirtualMachines.createVirtualMachine
Error type: Error
Error Message: Command "ssh-keygen -t rsa -b 4096 -f "C:\Users\Thomas\.ssh\azure_DiscordBot_rsa" -N "***"" failed with exit code "1":
Saving key "C:\\Users\\Thomas\\.ssh\\azure_DiscordBot_rsa" failed: No such file or directory
Generating public/private rsa key pair.

Version: 0.1.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:127:278753
rejected extension.bundle.js:127:278278
```

</details>

**Comment by nturinski** [comment] 2020-04-29 21:52
Closing as dupe of https://github.com/microsoft/vscode-azurevirtualmachines/issues/87

But the solution for you is to create a `.ssh` folder where it says there is "No such file or directory."

**Closed by nturinski** 2020-04-29 21:52 UTC
