### ISSUE TITLE
devtestlab linux machine via ssh connection problem

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-azurevirtualmachines#221] opened 2021-03-23 03:59 UTC
Does this occur consistently?  Yes
Repro steps:
1. make a devtestlab and one ubuntu virtual machine
2. choose the machine on vscode and click "connect to host via remote ssh"
3. the following error happened

Action: azureVirtualMachines.openInRemoteSsh
Error type: Error
Error Message: Internal error: Expected value to be neither null nor undefined: id

Version: 0.3.0
OS: win32
OS Release: 10.0.21337
Product: Visual Studio Code
Product Version: 1.54.1
Language: en

<details>
<summary>Call Stack</summary>

```
nonNullValue extension.bundle.js:16:26986
Object.nonNullValueAndProp extension.bundle.js:16:27215
VirtualMachineTreeItem.<anonymous> extension.bundle.js:16:68505
fulfilled extension.bundle.js:16:66608
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by nturinski** [comment] 2021-05-12 23:42
Closing as a dupe of https://github.com/microsoft/vscode-azurevirtualmachines/issues/172

**Closed by nturinski** 2021-05-12 23:42 UTC
Labels: bug, duplicate
