### ISSUE TITLE
Make sure that "VM" is included for search

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurevirtualmachines#120] opened 2020-06-16 21:56 UTC
Searching the marketplace for "Azure VM" doesn't show the extension. :(

**Comment by EricJizbaMSFT** [comment] 2020-06-16 21:58
Dupe of https://github.com/microsoft/vscode-azurevirtualmachines/issues/106

**Closed by EricJizbaMSFT** 2020-06-16 21:58 UTC
