### ISSUE TITLE
Fails on finding ...\.ssh folder

### ISSUE THREAD

**Issue by ctahok** [microsoft/vscode-azurevirtualmachines#88] opened 2020-03-10 13:05 UTC
It fails with below message:
Created new subnet "default".
Creating new network interface "VCCodeVM767"...
Created new network interface "VCCodeVM767".
Generating public/private rsa key pair in "C:\Users\myprofile**\.ssh\**azure_VCCodeVM_rsa"...
Error: ***C***o***m***m***a***n***d*** ***"***s***s***h***-***k***e***y***g***e***n*** ***-***t*** ***r***s***a*** ***-***b*** ***4***0***9***6*** ***-***f*** ***"***C***:***\***U***s***e***r***s***\***i***l***k***i***n***j***a***1***\***.***s***s***h***\***a***z***u***r***e***_***V***C***C***o***d***e***V***M***_***r***s***a***"*** ***-***N*** ***"***"***"*** ***f***a***i***l***e***d*** ***w***i***t***h*** ***e***x***i***t*** ***c***o***d***e*** ***"***1***"***:***
***
***S***a***v***i***n***g*** ***k***e***y*** ***"***C***:***\***\***U***s***e***r***s***\***\***i***l***k***i***n***j***a***1***\***\***.***s***s***h***\***\***a***z***u***r***e***_***V***C***C***o***d***e***V***M***_***r***s***a***"*** ***f***a***i***l***e***d***:*** ***N***o*** ***s***u***c***h*** ***f***i***l***e*** ***o***r*** ***d***i***r***e***c***t***o***r***y***
***
***G***e***n***e***r***a***t***i***n***g*** ***p***u***b***l***i***c***/***p***r***i***v***a***t***e*** ***r***s***a*** ***k***e***y*** ***p***a***i***r***.***
***
***

There is no .ssh folder under C:\Users\myprofile\ besides I even installed Remote-SSH extension

**Comment by nturinski** [comment] 2020-03-18 22:17
Create the `.ssh` folder for the user if it doesn't exist

**Comment by nturinski** [comment] 2020-03-18 22:19
Closing as a dupe of https://github.com/microsoft/vscode-azurevirtualmachines/issues/87

**Closed by nturinski** 2020-03-18 22:19 UTC
Labels: bug
